/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Users',
      [
        {
          username: 'John',
          email: 'john@gmail.com',
          password: 'jdf123',
          picture: 'https://i.postimg.cc/7ZNJyJjz/1.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Анна',
          email: 'anna@gmail.com',
          password: 'ann123',
          picture: 'https://i.postimg.cc/15nKPBKq/2.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Олег',
          email: 'oleg@gmail.com',
          password: 'orllksk543',
          picture: 'https://i.postimg.cc/DzFQrT3r/3.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Кирилл',
          email: 'kir@gmail.com',
          password: 'kirjjh',
          picture: 'https://i.postimg.cc/sDh5bXVP/4.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Сергей',
          email: 'serega@gmail.com',
          password: 'serega',
          picture: 'https://i.postimg.cc/L4qy6m95/5.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Демид',
          email: 'mexico@gmail.com',
          password: 'arriva',
          picture: 'https://i.postimg.cc/BbDc5QbC/6.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Janpol',
          email: 'janpol@gmail.com',
          password: 'jannn123',
          picture: 'https://i.postimg.cc/WzMgFWYW/7.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Jiro',
          email: 'ji@gmail.com',
          password: 'jiji009',
          picture: 'https://i.postimg.cc/G2DsVgRL/8.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Roberto',
          email: 'rob@gmail.com',
          password: 'robber',
          picture: 'https://i.postimg.cc/7LGCJtf3/9.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Margo',
          email: 'margo@gmail.com',
          password: 'mrmr',
          picture: 'https://i.postimg.cc/02yyJX4z/10.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Jenya',
          email: 'jenya@gmail.com',
          password: 'sombrero2000',
          picture: 'https://i.postimg.cc/x1bYKw31/11.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Andro',
          email: 'andronito@gmail.com',
          password: '500tequilas',
          picture: 'https://i.postimg.cc/HWZCFYSL/12.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Evgen',
          email: 'chichipo@gmail.com',
          password: 'evgenito',
          picture: 'https://i.postimg.cc/pV1gq0Th/13.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Otto',
          email: 'otto@gmail.com',
          password: 'otisto123',
          picture: 'https://i.postimg.cc/sXH0HXVd/14.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Juan',
          email: 'Juan@gmail.com',
          password: 'juan123',
          picture: 'https://i.postimg.cc/WzMgFWYW/7.png',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Margarita',
          email: 'mrgaysina@gmail.com',
          password: '123',
          picture: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          username: 'Evgeniy',
          email: 'Evgeniy3234@gmail.com',
          password: '123',
          picture: '',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
